# See: https://docs.docker.com/compose/compose-file/

version: "3.7"
services:
  db:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
  nsqd:
    image: nsqio/nsq
    ports:
      - "4150:4150"
      - "4151:4151"
    command: /nsqd
